### ISSUE TITLE
[p should be forced to paste linewise

### ISSUE THREAD

**Issue by kuator** [zmaas/evil-unimpaired#7]
[p doesn't paste on new line if register doesn't include new line

**Comment by mcp292** [comment]
This seems to work now.

**Comment by kuator** [comment]
> This seems to work now.

But the repo hasn't been updated since my comment was posted

**Comment by kuator** [comment]
> 

Checked it, it doesn't

**Comment by kuator** [comment]
> This seems to work now.

Nevermind, turns out somebody recently answered this same issue: https://emacs.stackexchange.com/questions/64726/is-it-possible-to-replicate-vim-unimpaired-p-paste-behaviour
